<?php

function sanitize_output($buffer) {

    $search = array(
        '/\>[^\S ]+/s',  // strip whitespaces after tags, except space
        '/[^\S ]+\</s',  // strip whitespaces before tags, except space
        '/(\s)+/s'       // shorten multiple whitespace sequences
    );

    $replace = array(
        '>',
        '<',
        '\\1'
    );

    $buffer = preg_replace($search, $replace, $buffer);

    return $buffer;
}

ob_start("sanitize_output");

?>

<!DOCTYPE html>

<!--[if lt IE 7 ]> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js"> <!--<![endif]-->

<head>
  <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
   <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,400italic' rel='stylesheet' type='text/css'>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('header') ?>

<?php 
	$_category = Mage::registry('current_category');
  $_path = $_category->getPath();
  $_ids = explode('/', $_path);
  if (isset($_ids[2])) {
      $_topParent = Mage::getModel('catalog/category')->setStoreId(Mage::app()->getStore()->getId())->load($_ids[2]);
      if ($_topParent->getFeaturedimage()) :
      $_imgUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/category/'.$_topParent->getFeaturedimage();
      endif;
  }
	else {
     $_topParent = null;//it means you are in one catalog root.
  }

?>

<section class="internal-splash category-internal-splash" <?php if ($_imgUrl) :?>style="background-image: url(<?php echo $_imgUrl;?>);"<?php endif;?>></section>
  <section class="category-view">
    <div class="row">


      <?php if($_category->getResource()->getAttribute('hasregions')->getFrontend()->getValue($_category) != 0){?>
      <div class="medium-6 columns">
        <h1><?php if (Mage::registry('current_category')) {
          echo Mage::registry('current_category')->getName();
    }
      else {
          $categoryIds = $_product->getCategoryIds();
          if (count($categoryIds)) {
              $firstCategoryId = $categoryIds[0];
              $_category = Mage::getModel('catalog/category')->load($firstCategoryId);

              echo $_category->getName();
          }
      }?></h1>
        <?php echo Mage::registry('current_category')->getDescription();?>
      </div>
      <?php } else {?>
      <div class="not-regional">
      <h1><?php if (Mage::registry('current_category')) {
          echo Mage::registry('current_category')->getName();
    }
      else {
          $categoryIds = $_product->getCategoryIds();
          if (count($categoryIds)) {
              $firstCategoryId = $categoryIds[0];
              $_category = Mage::getModel('catalog/category')->load($firstCategoryId);

              echo $_category->getName();
          }
      }?></h1>
        <?php echo Mage::registry('current_category')->getDescription();?>
        </div>
      <?php }?>
    </div>

    <!-- Products -->
    <div class="row category-products">

      <?php

      $categoryid = $_category->getCategoryIds;
      $_category->load($categoryid);
      $collection = $_category->getProductCollection();
      $collection->addAttributeToSelect('*');
      $collection->addAttributeToSort('name', 'ASC');
      $productcount = sizeof($collection);
      if($productcount == 2){
        $productcolumn = 6;
      } else {
        $productcolumn = 4;
      }
      foreach ($collection as $_product) { ?>

      <div class="medium-<?=$productcolumn;?> columns product-container" >
      <?php  if (($_product->getData('region') != NULL) && ($_product->getData('region') != 'no_selection')):?>                                     
                <div id="region"><img class="region-pic" src="<?php  echo $this->helper('catalog/image')->init($_product, 'region');?>" /></div>
            <?php endif; ?>
        <a href="<?php echo $_product->getProductUrl() ?>" >
          <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->keepAspectRatio(false)->keepFrame(FALSE)->resize(300, 225);?>" width="300" height="225">
        </a>
        <a href="<?php echo $_product->getProductUrl(); ?>"><h3><?php echo $_product->getName(); ?></h3></a>
        <a href="<?php echo $_product->getProductUrl(); ?>" class="button">Details</a>
      </div>

      <?php } ?>
          </div>

    <!-- Subcategories -->
    <div class="row subcategories">
    <?php
    if (isset($_category) && !empty($_category) && is_object($_category)) {
        // Create category collection for children
        $childrenCollection = $_category->getCollection();
        // Only get child categories of parent cat
        $childrenCollection->addIdFilter($_category->getChildren());
        // Only get active categories
        $childrenCollection->addAttributeToFilter('is_active', 1);
        // Add base attributes
        $childrenCollection->addAttributeToSelect('url_key')
                ->addAttributeToSelect('name')
                ->addAttributeToSelect('all_children')
                ->addAttributeToSelect('is_anchor')
                ->setOrder('position', Varien_Db_Select::SQL_ASC)
                ->joinUrlRewrite();
        // Add Image

        // How many subcategories do we have? Let's build our grid properly
        $childrenCollection->addAttributeToSelect('image');
        $count = sizeof($childrenCollection);
        if($count == 2){
          $column = 6;
        } else {
          $column = 4;
        }
        $counter = 0;
        if (count($childrenCollection) > 0) {?>
        <h1>Categories</h1><?php
            foreach($childrenCollection as $subcat) {
                if ($subcat->getIsActive()) {
                    $subcatName = $subcat->getName();
                    $subcatURL = $subcat->getUrl();
                    $subcatThumb = $subcat->getImageUrl();?>
                  <?php if($counter % 3 ==0){echo '<br style="clear:both">';} ?>
                  <div class="medium-<?=$column;?> columns subcategory-container">
                    <a href="<?=$subcatURL;?>"><img src="<?=$subcatThumb;?>" alt="" width="300" height="225" style="width: 300px; height: 225px; "></a>
                    <h3><a href="<?=$subcatURL;?>"><?=$subcatName;?></a></h3>
                    <a href="<?=$subcatURL;?>" class="button">View Products</a>
                  </div>
                <?php }
              $counter++;
            }
        }
    }?>
    </div>
    <div class="row">
      <div class="category-body-text">
        <?php echo $_category->getData('catbodytext') ; ?>
      </div>
    </div>
  </section>
        <?php echo $this->getChildHtml('footer_before') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
