<?php

function sanitize_output($buffer) {

    $search = array(
        '/\>[^\S ]+/s',  // strip whitespaces after tags, except space
        '/[^\S ]+\</s',  // strip whitespaces before tags, except space
        '/(\s)+/s'       // shorten multiple whitespace sequences
    );

    $replace = array(
        '>',
        '<',
        '\\1'
    );

    $buffer = preg_replace($search, $replace, $buffer);

    return $buffer;
}

ob_start("sanitize_output");

?>

<!DOCTYPE html>

<!--[if lt IE 7 ]> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js"> <!--<![endif]-->

<head>
  <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
   <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,400italic' rel='stylesheet' type='text/css'>
<?php echo $this->getChildHtml('head') ?>
<script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?> id="contact-page">
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=351377081548057";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
  <section class="internal-splash contact-internal-splash"></section>
  <section class="contact-form">
    <div class="row">
      <h3>Contact Nature's Seed</h3>
      <div class="medium-8 columns">
        <h3>Fill out our online form</h3>
        <p>At NaturesFinestSeed.com we strive for the best customer experience possible. We appreciate your comments, feedback, and questions.</p>
        <p>Our seed experts will quickly reply to any question. For questions about what seed to plant, recommendations and specific planting needs our seed experts need as much geographic and soil information as possible. Please include your city, state and zip code. Information regarding sunlight and water is also important.</p>

        <form>
          <h4>Personal Information</h4>
          <div class="control-group">
            <label for="name">Your Full Name *</label>
            <input type="text" class="text">
          </div>
          <div class="control-group">
            <label for="email">Your Email Address *</label>
            <input type="text" class="text">
          </div>
          <div class="control-group">
            <label for="phone">Phone Number</label>
            <input type="text" class="text">
          </div>
          <div class="control-group">
            <label for="subject">Subject</label>
            <input type="text" class="text">
          </div>
          <div class="control-group">
            <label for="message">Question / Message *</label>
            <textarea name="" id="" cols="30" rows="20"></textarea>
          </div>
          <h5>** Optional additional information to help us better serve you</h5>
          <h4>Planting Location</h4>
          <div class="control-group">
            <label for="city">Nearest City</label>
            <input type="text" class="text">
          </div>
          <div class="control-group">
            <label for="state">Nearest State</label>
            <select>
              <option value="AL">Alabama</option>
              <option value="AK">Alaska</option>
              <option value="AZ">Arizona</option>
              <option value="AR">Arkansas</option>
              <option value="CA">California</option>
              <option value="CO">Colorado</option>
              <option value="CT">Connecticut</option>
              <option value="DE">Delaware</option>
              <option value="DC">District Of Columbia</option>
              <option value="FL">Florida</option>
              <option value="GA">Georgia</option>
              <option value="HI">Hawaii</option>
              <option value="ID">Idaho</option>
              <option value="IL">Illinois</option>
              <option value="IN">Indiana</option>
              <option value="IA">Iowa</option>
              <option value="KS">Kansas</option>
              <option value="KY">Kentucky</option>
              <option value="LA">Louisiana</option>
              <option value="ME">Maine</option>
              <option value="MD">Maryland</option>
              <option value="MA">Massachusetts</option>
              <option value="MI">Michigan</option>
              <option value="MN">Minnesota</option>
              <option value="MS">Mississippi</option>
              <option value="MO">Missouri</option>
              <option value="MT">Montana</option>
              <option value="NE">Nebraska</option>
              <option value="NV">Nevada</option>
              <option value="NH">New Hampshire</option>
              <option value="NJ">New Jersey</option>
              <option value="NM">New Mexico</option>
              <option value="NY">New York</option>
              <option value="NC">North Carolina</option>
              <option value="ND">North Dakota</option>
              <option value="OH">Ohio</option>
              <option value="OK">Oklahoma</option>
              <option value="OR">Oregon</option>
              <option value="PA">Pennsylvania</option>
              <option value="RI">Rhode Island</option>
              <option value="SC">South Carolina</option>
              <option value="SD">South Dakota</option>
              <option value="TN">Tennessee</option>
              <option value="TX">Texas</option>
              <option value="UT">Utah</option>
              <option value="VT">Vermont</option>
              <option value="VA">Virginia</option>
              <option value="WA">Washington</option>
              <option value="WV">West Virginia</option>
              <option value="WI">Wisconsin</option>
              <option value="WY">Wyoming</option>
              <option value="AS">American Samoa</option>
              <option value="GU">Guam</option>
              <option value="MP">Northern Mariana Islands</option>
              <option value="PR">Puerto Rico</option>
              <option value="UM">United States Minor Outlying Islands</option>
              <option value="VI">Virgin Islands</option>
              <option value="AA">Armed Forces Americas</option>
              <option value="AP">Armed Forces Pacific</option>
              <option value="AE">Armed Forces Others</option>
            </select>


          </div>
          <div class="control-group">
            <label for="zip">Zip Code</label>
            <input type="text" class="text zipcode">
          </div>
          <div class="g-recaptcha" data-sitekey="6LfVyRcTAAAAAEvkI4FpeMAbqSyEUgJzkTgm-Wfv"></div>
          <button class="button" type="submit">Submit Form</button>
        </form>
      </div>
      <div class="medium-4 columns">
        <a href="javascript:void($zopim.livechat.say('Hello!'))" class="button live-chat-link"><i class="fa fa-comments"></i> Live Chat</a>
        <div class="fb-page" data-href="https://www.facebook.com/NaturesFinestSeed/?fref=ts" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/NaturesFinestSeed/?fref=ts"><a href="https://www.facebook.com/NaturesFinestSeed/?fref=ts">NaturesFinestSeed.com</a></blockquote></div></div>
        <h3>Recent Testimonials</h3>
        <div class="testimonial-excerpt">
          <p class="quote">“We have purchased both Pasture Blend and Blue Ribbon Turf Blend from Nature's Seed and have loved both products. I recommend Nature's Seed to all my friends."</p>
          <p class="author">Angeline Carson</p>
          <p class="title">Carson Custom Hardwood</p>
        </div>
        <div class="testimonial-excerpt">
          <p class="quote">"Our lawn is the greenest on our block. Whenever anyone asks, we tell them that we got the seed from NaturesFinestSeed.com."</p>
          <p class="author">Jakob Murphy</p>
          <p class="title">Homeowner</p>
        </div>
        <div class="testimonial-excerpt">
          <p class="quote">“The experts at Nature’s Seed have consistently provided exceptional knowledge and customer service along with the best quality seed in helping my company meet its reclamation objectives.”</p>
          <p class="author">Mark Stewart</p>
          <p class="title">Questar Pipeline Company</p>
        </div>
      </div>
    </div>
  </section>
  <section class="featured">
    <div class="row">
      <h3>Nature's Seed Has Been Featured On</h3>
      <img src="<?php echo $this->getSkinUrl('images/featured.png');?>" alt="Nature's Seed Featured Networks">
    </div>
  </section>
  <section class="testimonials">
    <div class="row">
      <h3>People Love Nature's Seed</h3>
      <h4>We have thousands of happy customers! We like to think of ourselves as a leader in the community, and we thank you for trusting us as your seed provider.</h4>
      <div class="medium-4 columns">
        <div class="testimonial">
          <div class="icon"><i class="fa fa-comments-o"></i></div>
          <p class="quote">“The experts at Nature’s Seed have consistently provided exceptional knowledge and customer service along with the best quality seed in helping my company meet its reclamation objectives.”</p>
          <p class="author">Mark Stewart</p>
          <p class="title">Questar Pipeline Company</p>
        </div>
      </div>
      <div class="medium-4 columns">
        <div class="testimonial">
          <div class="icon"><i class="fa fa-comments-o"></i></div>
          <p class="quote">"...we appreciate the wildflower seed assortment we get from you. They are a wonderful assortment and it’s nice to get a mix that changes through the season. Our back yard looks great all summer!"</p>
          <p class="author">Greg White</p>
        <p class="title">Cabin Owner</p>
      </div>
      </div>
      <div class="medium-4 columns">
        <div class="testimonial">
          <div class="icon"><i class="fa fa-comments-o"></i></div>
          <p class="quote">"I’ve been re-seeding mining disturbances for 25 years and have yet to find a company with better seed quality, seed selection and customer relations."<br><br></p>
          <p class="author">Greg E. Jones</p>
          <p class="title">Environmental Scientist</p>
        </div>
      </div>
    </div>
    <div class="row">
      <a href=/testimonial/ class="button">Read More Testimonials</a>
    </div>
  </section>
        <?php echo $this->getChildHtml('footer_before') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
