  <div class="home-slider">
    <section class="splash lawn">
      <div class="row">
        <h1>Lawn Seed Blends</h1>
        <h2>Highest Quality Grass Seed</h2>
        <div class="button-container columns medium-6 medium-centered"><a href="/about" class="button">Learn More</a><a href="/grass-seed.html" class="button">Shop Now</a></div>
      </div>
    </section>
    <section class="splash pasture">
      <div class="row">
        <h1>Native Pasture Seed</h1>
        <h2>Top Tier Pacific Southwest Seed</h2>
        <div class="button-container columns medium-6 medium-centered"><a href="/about" class="button">Learn More</a><a href="/pasture-seed.html" class="button">Shop Now</a></div>
      </div>
    </section>
    <section class="splash wildflower">
    <div class="row">
      <h1>Naturalized Wildflower Seed</h1>
      <h2>Beautiful Eye-Catching Wildflowers</h2>
      <div class="button-container columns medium-6 medium-centered"><a href="/about" class="button">Learn More</a><a href="/wildflower-seed.html" class="button">Shop Now</a></div>
    </div>
  </section>
  <section class="splash speciality">
    <div class="row">
      <h1>Solve Problems with Specialty Blends</h1>
      <h2>Having Challenges? Try our Specialty Blend</h2>
      <div class="button-container columns medium-6 medium-centered"><a href="/about" class="button">Learn More</a><a href="/specialty-seed.html" class="button">Shop Now</a></div>
    </div>
  </section>
  </div>