<?php
/**
 * How to call in CMS page
 * {{block type='mageplaza_betterblog/post_recent'  post_count="1" block_name="Latest from the blog" template='mageplaza_betterblog/post/recent.phtml'}}
 * {{block type='mageplaza_betterblog/post_cat'  post_count="1" category_id="4" block_name="Latest news" template='mageplaza_betterblog/post/recent.phtml'}}
 */
?>

<?php $posts = $this->getPosts(); ?>
<?php $postCount = $this->getPostCount(); ?>
<?php $i=0; ?>
    <div class="grid12-4">

        <div class="feature">

            <?php foreach ($posts as $post): ?>
			<div class="medium-6 columns post">            
                <?php if($i >= $postCount) break;?>
                    <?php if ($post->getImage()) :?>
                        <a href="<?php echo $post->getPostUrl(); ?>" alt="<?php echo $post->getPostTitle(); ?>" title="<?php echo $post->getPostTitle(); ?>"><img src="<?php echo Mage::helper('mageplaza_betterblog/post_image')->init($post, 'image');?>" alt="<?php echo $post->getPostTitle(); ?>" title="<?php echo $post->getPostTitle(); ?>" /></a>
                    <?php endif;?>
					<div class="post-content">	                
		                <h1 class="post-title"><a href="<?php echo $post->getPostUrl(); ?>" alt="<?php echo $post->getPostTitle(); ?>" title="<?php echo $post->getPostTitle(); ?>"><?php echo $post->getPostTitle(); ?></a></h1>
                    <p><?php 
						  $wordsreturned = 25;
						  $string = $post->getPostExcerpt();
						  $retval = $string;
						  $string = strip_tags($string);
						  $string = preg_replace('/(?<=\S,)(?=\S)/', ' ', $string);
						  $string = str_replace("\n", " ", $string);
						  $array = explode(" ", $string);
						  if (count($array)<=$wordsreturned)
						  {
						    $retval = $string;
						  }
						  else
						  {
						    array_splice($array, $wordsreturned);
						    $retval = implode(" ", $array)." ...";
						  }
						  echo $retval;	                    
	                 ?></p>
                    <a class="button" href="<?php echo $post->getPostUrl(); ?>" alt="<?php echo $post->getPostTitle(); ?>" title="<?php echo $post->getPostTitle(); ?>">Read More</a>
                   	</div>
                <?php $i++; ?>
			</div>
            <?php endforeach; ?>

        </div>

    </div>
