<div class="fixed-header">
<div class="top-bar">
    <div class="row row-contained">
      <div class="medium-2 columns">
        <ul class="inline-list social-links">
          <li><a href="https://www.facebook.com/NaturesFinestSeed" target="_blank"><i class="fa fa-facebook-square"></i></a></li>
          <li><a href="https://twitter.com/nature_seeds" target="_blank"><i class=" fa fa-twitter"></i></a></li>
          <li><a href="https://www.instagram.com/natures_seed/" target="_blank"><i class="fa fa-instagram"></i></a></li>
          <li><a href="https://www.youtube.com/channel/UCUBhUh_H5I1zwZoXVTSzUPg" target="_blank"><i class="fa fa-youtube"></i></a></li>
        </ul>
      </div>
      <div class="medium-10 columns">
        <ul class="inline-list right">
          <li><div class="search-form"><?php echo $this->getChildHtml('topSearch') ?></div><a href="#" class="search-toggle"></a>
          </li>
          <li><a href="/about">About</a></li>
          <li><a href="/testimonials">Testimonials</a></li>
          <li><a href="/contact">Contact</a></li>
          <li><a href="/customer/account/login/">Login</a></li>
          <li><a href="javascript:void($zopim.livechat.say('Hello!'))" class="live-chat-link">Live Chat</a></li>
          <li><a href="<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>">Cart</a></li>
        </ul>
      </div>
    </div>
  </div>
  <header class="primary-header">
    <div class="row row-contained">
      <div class="medium-4 columns"><a href="/"><img src="<?php echo $this->getSkinUrl('images/primary-logo.png');?>" alt="Nature's Seed Logo"></a></div>
      <div class="medium-3 columns right"><img src="<?php echo $this->getSkinUrl('images/shipping.png');?>" alt="Nature's Seed Free Shipping" class="shipping"></div>
    </div>
  </header>


  <div class="primary-navigation">	  
    <div class="row row-contained">
      <ul class="inline-list">
        <li class="dropdown-toggle">
          <a href="/grass-seed.html">Lawn Grass Seed <i class="fa fa-caret-down"></i></a>
          <ul>
            <!-- <li><a href="/grass-lawn-seeds.html">Grass Seeds By Region</a></li> -->
            <li><a href="http://naturesfinest.searchbloom.net/grass-seed/ornamental-grasses.html">Ornamental Grasses</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/grass-seed/ornamental-grasses.html">Ornamental Grasses</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/grass-seed/lawn-grass-seed-types.html">Lawn Grass Seed Types</a>
            </li>
            <li><a href="http://naturesfinest.searchbloom.net/grass-seed/kentucky-blue-grass.html">-  Kentucky Blue Grass Seeds</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/grass-seed/perennial-ryegrass.html">
            -  Perennial Ryegrass Seeds</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/grass-seed/fescue-grass-seeds.html">-  Fescue Grass Seeds</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/grass-seed/bahia-grass-seeds.html">-  Bahia Grass Seeds</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/grass-seed/bermuda-grass-seeds.html">-  Bermuda Grass Seeds</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/grass-seed/buffalograss-seeds.html">-  Buffalograss Seeds</a></li>
          </ul>
        </li>
        <li><a href="/wildflower-seed.html">Wildflower Seed <i class="fa fa-caret-down"></i></a>
          <ul>
            <li><a href="/wildflower-seed/regional-wildflowers.html">Regional Wildflower Mixes</a></li>
            <li><a href="/wildflower-seed/native-wildflower-seeds.html">Native Wildflower Seeds</a></li>
          </ul>
        </li>
        <li><a href="/pasture-seed.html">Pasture Seed <i class="fa fa-caret-down"></i></a>
          <ul>
            <li><a href="http://naturesfinest.searchbloom.net/pasture-seed/pasture-seed-blend-types/cattle-forage.html">-  Cattle Pastures</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/pasture-seed/pasture-seed-blend-types/horse-forage.html">-  Horse Pastures</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/pasture-seed/pasture-seed-blend-types/sheep-forage.html">-  Sheep Pastures</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/pasture-seed/pasture-seed-blend-types/goat-forage.html">-  Goat Pastures</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/pasture-seed/pasture-seed-blend-types/alpaca-llama-forage.html">-  Alpaca/Llama Pastures</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/pasture-seed/pasture-seed-blend-types/bison-forage.html">-  Bison Pastures</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/pasture-seed/pasture-seed-blend-types/poultry-forage.html">-  Poultry Pastures</a></li>
            <li><a href="/tortoise-forage-blend.html">- Tortoise Forage Blend</a></li>
          </ul>
        </li>
        <li><a href="http://naturesfinest.searchbloom.net/specialty-seeds.html">Specialty Seed <i class="fa fa-caret-down"></i></a>
          <ul>
            <li><a href="http://naturesfinest.searchbloom.net/specialty-seeds/green-manure-cover-crops.html">- Green Manure Cover Crops</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/specialty-seeds/honey-bee-blends.html">- Honey Bee Blends</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/specialty-seeds/pollinator-seed-blends.html">- Pollinator Seed Blends</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/specialty-seeds/big-game-foot-plot-blends.html">- Big Game Food Plot Blends</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/specialty-seeds/upland-game-food-plot-blends.html">- Upland Game Food Plot Blends</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/specialty-seeds/erosion-control-blends.html">- Erosion Control Blends</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/specialty-seeds/wildfire-resistance-blends.html">- Wildfire Resistance Blends</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/specialty-seeds/wetland-restoration-blends.html">- Wetland Restoration Blends</a></li>
            <li><a href="http://naturesfinest.searchbloom.net/specialty-seeds/dryland-pasture-blends.html">- Dryland Pasture Blends</a></li>
          </ul>
        </li>
        <li><a href="/planting-aids.html">Planting Aids</a></li>
        <li><a href="/blog-posts">Blog</a></li>
        <li><a href="/resources">Resources</a></li>
      </ul>
    </div>
  </div>
  
  <?php /* echo $this->getChildHtml('topMenu') */ ?>
  
</div>

<?php echo $this->getChildHtml('topContainer'); ?>
